### ISSUE TITLE
K-Means - Base

### ISSUE THREAD

**Issue by SatYu26** [Algo-Phantoms/Algo-ScriptML#10]
Adding K means.

GSSoC'21

**Comment by gopichandpuli9** [comment]
Can I work on this

**Comment by SatYu26** [comment]
> Can I work on this

actually I have already pushed a PR for this

**Comment by SatYu26** [comment]
@ashwani-rathee can u please help me let me know what should I add or remove in order to make it a successful merge.

**Comment by ashwani-rathee** [comment]
@SatYu26  You have been assigned the task to setup the base for K Means.
Try to submit a PR in 5 days.

**Comment by ashwani-rathee** [comment]
@SatYu26 It's mostly linting issues,I will review it properly later today and also need to talk to our admin to know how strictly we talk linting issues.

**Comment by SatYu26** [comment]
@ashwani-rathee Sure sir. meanwhile, i will try to make it more precise and as soon as u will let me know I will change them.

**Comment by ashwani-rathee** [comment]
#11 is ready
