### ISSUE TITLE
Implementing Linear Regression from Scratch

### ISSUE THREAD

**Issue by spsrathor** [Algo-Phantoms/Algo-ScriptML#105]
There is no code of Linear Regression in its folder. I want to implement Linear Regression from Scratch.

Please assign this issue to me.

I am also member of GSSOC'21

**Comment by vedantagarwal4** [comment]
Hi ,
Could you please assign this issue to me? I will implement linear regression and provide the documentation as well. 
I am a member of GSSOC'21.

**Comment by Aditi1010** [comment]
Hi,
Could you assign this issue to me? I am a part of GSSOC 21. I will solve the problem at the earliest.

**Comment by Aj7t** [comment]
Hello, I am a part of GSSOC'21.
Could you assign this issue to me?  I will implement a Linear Regression from Scratch at the earliest.🚀

**Comment by pragyangra** [comment]
Greetings! As a participant of GSSOC'21 I want to contribute to this issue of the project. Can you please assign this to me?

**Comment by ashwani-rathee** [comment]
@spsrathor @Aditi1010 @pragyangra @vedantagarwal4 @Aj7t This has already been implemented both base and documentation,you can work toward improving them :)
