### ISSUE TITLE
Implementing Logistic Regression from Scratch

### ISSUE THREAD

**Issue by Abheeshth** [Algo-Phantoms/Algo-ScriptML#106]
There is no code and documentation of Logistic Regression in its folder. I want to implement the same from Scratch.
Please assign this issue to me.

I am also member of GSSOC'21

**Comment by Aj7t** [comment]
🚀hello, I am a member if Gssoc'21. plz assign me this issue, I do it  from scratch as earliest as possible

**Comment by jprakash-1** [comment]
Hello, I am Gssoc'21 participant. Please assign me this issue.

**Comment by ashwani-rathee** [comment]
Similarly possible duplicate
