### ISSUE TITLE
Adding code to Multilayer perceptron

### ISSUE THREAD

**Issue by Abheeshth** [Algo-Phantoms/Algo-ScriptML#107]
There is no code of Multilayer perceptron, I wanna implement same from Scratch.

I am also member of GSSOC'21

In anticipation of positive response.

**Comment by aayushi1908** [comment]
Hello.
I'm Aayushi, a GSSOC'21 participant and I want to work on this issue.

**Comment by Sibasish-Padhy** [comment]
hello,I'm Sibasish ,a GSSOC'21 participant and I would like to contribute to this issue

**Comment by ashwani-rathee** [comment]
@Abheeshth do you wish to take this up?

**Comment by ashwani-rathee** [comment]
#46 Duplicate

**Comment by Abheeshth** [comment]
> @Abheeshth do you wish to take this up?

yes I wanna take this up

**Comment by Abheeshth** [comment]
> @Abheeshth do you wish to take this up?

yes I wanna take this up
