### ISSUE TITLE
Update Naive Bayes Documentation

### ISSUE THREAD

**Issue by namaannn** [Algo-Phantoms/Algo-ScriptML#117]
Some of the major details regarding algorithm were missing as the main concept from which the algorithm is derived is not clearly understandable in the documentation and other tweaks are required in the documentation.

I want to raise this issue for Gssoc 2021.

**Comment by jaimehta1912** [comment]
i want to work on this issue .
I am a gssoc  2021 participant and have a deep knowledeg of ml
Kindly assign me this issue

**Comment by jaimehta1912** [comment]
@anubhavitis @SatYu26 @dheerajkotwani

**Comment by namaannn** [comment]
@anubhavitis @SatYu26 @dheerajkotwani 
Kindly label this issue for Gssoc 2021

**Comment by SatYu26** [comment]
> @anubhavitis @SatYu26 @dheerajkotwani
> Kindly label this issue for Gssoc 2021

Hello, I am also a Gssoc 21 applicant itself. please tag admins they might help.

**Comment by jaimehta1912** [comment]
@SatYu26  sir can you please tell who are the admins ?

**Comment by SatYu26** [comment]
> @SatYu26 sir can you please tell who are the admins ?

sorry I am not familiar with admins.

**Comment by ashwani-rathee** [comment]
#86 duplicate
