### ISSUE TITLE
Hidden Markov Models - Implementation

### ISSUE THREAD

**Issue by kad99kev** [Algo-Phantoms/Algo-ScriptML#124]
Hello! I am a GSSOC'21 participant and I would like to implement a Hidden Markov Model from scratch. Do let me know if it is a suitable addition to the project!

**Comment by ashwani-rathee** [comment]
@geekquad What do you think about this idea?I like it

**Comment by jaimehta1912** [comment]
@ashwani-rathee kindly assign me this issue I want to work on it

**Comment by geekquad** [comment]
Assigning you with the same @kad99kev.

**Comment by ashwani-rathee** [comment]
#134 is a work in progress
