### ISSUE TITLE
Hierarchical Clustering: Counting the number of clusters from dendrogram

### ISSUE THREAD

**Issue by AkhileshThite** [Algo-Phantoms/Algo-ScriptML#131]
GSSoC 21': 
I would like to add simple explanation with images (created by me) of Hierarchical Clustering, that'll explain how to "count" the number of clusters from dendrogram. Kindly assign me the issue :)
Thank you!

**Comment by geekquad** [comment]
Assigning you with the same @AkhileshThite

**Comment by AkhileshThite** [comment]
Thank you :)

**Comment by subhangi2731** [comment]
@geekquad please assign me this issue I will send the pr in 1 day

**Comment by yukti845** [comment]
@subhangi2731 go ahead.

**Comment by AkhileshThite** [comment]
> @geekquad please assign me this issue I will send the pr in 1 day

Hey! My PR for this issue is already merged #145
you can make changes in that if you want to :)

**Comment by yukti845** [comment]
@AkhileshThite I didn't know that your PR is already merged.

**Comment by AkhileshThite** [comment]
> @AkhileshThite I didn't know that your PR is already merged.

It's okay.
