### ISSUE TITLE
Principal component Analysis(PCA),K-Means, Logistic Regression, Linear regression 

### ISSUE THREAD

**Issue by captainra1** [Algo-Phantoms/Algo-ScriptML#14]
I am a GSSOC 21's participant and want to work on the algorithms- Principal component Analysis(PCA), K-Means, Logistic Regression, Linear regression. kindly assign me.

**Comment by Abhinaba006** [comment]
I am a GSSOC 21 participant, I will like to contribute, please assign me this

**Comment by Rutikab12** [comment]
Hi I am GSSoC'21 participant , I would love to contribute this algorithms. Kindly assign it to me.

**Comment by ashwani-rathee** [comment]
@Rutikab12 I have updated the issues list you can claim one of those among these.

**Comment by captainra1** [comment]
assign me PCA or K-means

**Comment by Sibasish-Padhy** [comment]
@ashwani-rathee please assign me with PCAas It would also help me for a better grasp

**Comment by ashwani-rathee** [comment]
All these have been assigned already for next 4 days,you can check the updated issues to see which issue is assigned and which is free.
