### ISSUE TITLE
Gaussian Mixture Model - Documentation

### ISSUE THREAD

**Issue by surbhi2408** [Algo-Phantoms/Algo-ScriptML#142]
I'm a gssoc'21 participant and would like to add this in your repo.
@geekquad @ashwani-rathee Please assign this issue to me.

**Comment by ashwani-rathee** [comment]
Please create a separate folder for this task.
You are assigned the task to create codebase for Gaussian Mixture Model

**Comment by surbhi2408** [comment]
Thank you for assigning.

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by ashwani-rathee** [comment]
No updates on this,this needs to be reassigned

**Comment by vinc3nati** [comment]
> No updates on this,this needs to be reassigned

Hey if permitted I am ready to take up this issue as I have pretty good knowledge about Gaussian Mixture Model.

**Comment by ashwani-rathee** [comment]
@vinc3nati Go ahead

**Comment by vinc3nati** [comment]
Hey @ashwani-rathee do I need to implement the code as well ?

**Comment by vinc3nati** [comment]
Hey @ashwani-rathee I have completed the code implementation of Gaussian Mixture Model as well so should I push it ? or the documentation is what expected ?
