### ISSUE TITLE
MultiLayer Pereceptron and Naive Bayes

### ISSUE THREAD

**Issue by NitiKaur** [Algo-Phantoms/Algo-ScriptML#15]
I want to work on these two folders as an initial task.Please assign it to me

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant. I have worked on a similar problem before and want to contribute to this issue. Kindly assign me this issue as a part of the GSSOC'21.

**Comment by NitiKaur** [comment]
I have also worked also worked on it. @skybluee2001  please look for some other issue! :)

**Comment by ashwani-rathee** [comment]
These have been assigned properly and proper channel for communication for these have been formed
