### ISSUE TITLE
 Dimensionality Reduction Algorithm

### ISSUE THREAD

**Issue by vinc3nati** [Algo-Phantoms/Algo-ScriptML#154]
I would like to contribute a proper implementation with python of  Dimensionality Reduction Algorithm with proper documentation and well explained steps.

**Comment by ashwani-rathee** [comment]
@vinc3nati Which dimensionality reduction algorithm? Can you name specific algorithm?
Since there are several of them :)

**Comment by vinc3nati** [comment]
> @vinc3nati Which dimensionality reduction algorithm? Can you name specific algorithm?
> Since there are several of them :)

I planned on providing a overall compact documentation of the dimensionality reduction algorithm with diagrams and all.
Then implementing either of the following with proper format:
- Principal Component Analysis (PCA)
- Linear Discriminant Analysis (LDA)
- Generalized Discriminant Analysis (GDA)

> I think pca has been implemented before so I can work on the either of the other two.

**Comment by vinc3nati** [comment]
> @vinc3nati Which dimensionality reduction algorithm? Can you name specific algorithm?
> Since there are several of them :)

Hey so I've decided to go with LDA and I want to contribute it's documentation + code implementation (python).
Can you assign me this ??

**Comment by ashwinraj-in** [comment]
I would also like to contribute for this issue. Since @vinc3nati is planning to work on LDA and documentation for PCA is already available, I will like to work on the python implementation of PCA and/or complete documentation-implementation of GDA.

**Comment by geekquad** [comment]
> > @vinc3nati Which dimensionality reduction algorithm? Can you name specific algorithm?
> > Since there are several of them :)
> 
> Hey so I've decided to go with LDA and I want to contribute it's documentation + code implementation (python).
> Can you assign me this ??

Sure, go ahead with LDA.

**Comment by geekquad** [comment]
> @ashwani-rathee // I would also like to contribute for this issue. Since @vinc3nati is planning to work on LDA and documentation for PCA is already available, I will like to work on the python implementation of PCA and/or complete documentation-implementation of GDA.

Go ahead with GDA.

**Comment by ashwani-rathee** [comment]
Addressed in #186
