### ISSUE TITLE
K Nearest Neighbours

### ISSUE THREAD

**Issue by gopichandpuli9** [Algo-Phantoms/Algo-ScriptML#16]
Can I work on this issue as a part of GSSoC?

**Comment by aditiaggarwal28** [comment]
I'm a GSSOC'21 participant and will contribute to this issue using c++ language. 
Requesting admins to please assign this issue to me.

**Comment by Amit366** [comment]
Can I work on this issue??

**Comment by nNikita1018** [comment]
I want to work with this issue

**Comment by SSHREYA71** [comment]
I would like to work on this issue

**Comment by simarjeet30** [comment]
Hello @kritikaparmar-programmer.
I am a GSSOC'21 participant. I would like to work on the issue of the K Nearest Neighbours Algorithm using any of my three languages. I know python , C , C++ well. And i also have a good knowledge on DSA .Please assign this issue to me.

**Comment by ashwani-rathee** [comment]
Proper issue has been formed for this and it will cause more confusion if we keep this @simarjeet30 @gopichandpuli9 pls make KNN-documentation issue,since KNN-base has already been assigned

**Comment by simarjeet30** [comment]
@ashwani-rathee  what am I supposed to do in  KNN-documentation issue ?

**Comment by ashwani-rathee** [comment]
@simarjeet30,you are assigned Random Forest Base,please try to do only one thing at a time :)
