### ISSUE TITLE
Bayesian Regression - Documentation

### ISSUE THREAD

**Issue by gopichandpuli9** [Algo-Phantoms/Algo-ScriptML#17]
Could you please assign me this issue

**Comment by Khushi1408** [comment]
I would like to work on this issue. I will code it using python.

**Comment by ashwani-rathee** [comment]
Task:  Update the Readme.md to explain the process behind Bayesian Regression as well as you can 
Level-1 : 10 Points

**Comment by ashwani-rathee** [comment]
@Khushi1408 would you like to take this task?

**Comment by gopichandpuli9** [comment]
@ashwani-rathee I've raised this issue first. Please assign this to me!

**Comment by ashwani-rathee** [comment]
@gopichandpuli9 It was decided by project admin and mentors that the issue is assigned to someone who has asked for the claim on issue in last 2 days first.I would wait for 1 hr for @Khushi1408 to respond,otherwise I will assign you :)

**Comment by Sibasish-Padhy** [comment]
can i work on this issue??

**Comment by ashwani-rathee** [comment]
Sure @Sibasish-Padhy ,You have been assigned the task to create detailed documentation of Bayesian Regression.
Try to submit a PR in 2 days.

**Comment by Khushi1408** [comment]
Yes sure

**Comment by Khushi1408** [comment]
I apologize for late reply, it wont happen again, can you assign me some
other task?

**Comment by ashwani-rathee** [comment]
@Khushi1408 I have created 2 more documentation tasks ,you can claim one of those

**Comment by ashwani-rathee** [comment]
@Sibasish-Padhy #75 is almost ready,but please update it to format it a little better

**Comment by ashwani-rathee** [comment]
Good work @Sibasish-Padhy
