### ISSUE TITLE
Markov's Chain

### ISSUE THREAD

**Issue by Aparna-Sakshi** [Algo-Phantoms/Algo-ScriptML#178]
A Markov chain essentially consists of a set of transitions determined by some probability distribution that satisfies the Markov property.

I would like to implement Markov's chain from scratch with a detailed explanation. Please assign me this issue @ashwani-rathee .

**Comment by geekquad** [comment]
Go ahead @Aparna-Sakshi.

**Comment by yukti845** [comment]
@Aparna-Sakshi We need some updates on this issue

**Comment by Dishita2602** [comment]
I can work if no work is done yet

**Comment by Aparna-Sakshi** [comment]
I have already coded Markov's chain from scratch. Will provide a detailed explanation and submit a pr by today. I am extremely sorry for the delay.

**Comment by geekquad** [comment]
Transferring this to @Dishita2602. Make a PR by 30th.

**Comment by Dishita2602** [comment]
> Transferring this to @Dishita2602. Make a PR by 30th.

Do I need to make separate folder for Markov's chain ? 

@geekquad

**Comment by geekquad** [comment]
Yes @Dishita2602.
