### ISSUE TITLE
D203 and D211 are in conflict

### ISSUE THREAD

**Issue by psyduck1203** [Algo-Phantoms/Algo-ScriptML#18]
![Screenshot_2021-03-09 Algo-ScriptML - Codacy - Commits(1)](https://user-images.githubusercontent.com/58680590/110423752-a4671b80-80c7-11eb-8f5a-9d2be49134ad.png)

![Screenshot_2021-03-09 Algo-ScriptML - Codacy - Commits](https://user-images.githubusercontent.com/58680590/110423728-974a2c80-80c7-11eb-8499-d2df4f01515a.png)

I tried a lot of commits and changes to the code and then after googling I realized that it is mentioned in the [pydocstyle issues](https://github.com/PyCQA/pydocstyle/issues/141) that D203 and D211 i.e.

`D203: 1 blank line required before class docstring1`
`D211: No blank lines allowed before class docstring`

are conflicting and one of them should be disabled and hence any of the pull requests were not up to the standards and showing some or the other checks as failed.

**Comment by psyduck1203** [comment]
@geekquad, @plazzy99 please look at this issue.

**Comment by geekquad** [comment]
Hey @psyduck1203, the webhooks we were using were not trained and thus were throwing errors. 
Please try again and you will be good to go.
Let me know if you face any difficulties.
