### ISSUE TITLE
SVM -Documentation 

### ISSUE THREAD

**Issue by ainy-123** [Algo-Phantoms/Algo-ScriptML#180]
I am GSSoC'21 participant and I want to work on this issue.
Kindly assign this to me. @geekquad @ashwani-rathee

**Comment by sameeksharl** [comment]
I would like to work on this issue ?? could u pls assign me ?? @geekquad

**Comment by sameeksharl** [comment]
@ashwani-rathee @geekquad could you pls assign this to me??
