### ISSUE TITLE
Update Readme.md for GA

### ISSUE THREAD

**Issue by Dishita2602** [Algo-Phantoms/Algo-ScriptML#181]
I would like to work on this issue. please assign me

**Comment by geekquad** [comment]
Go ahead @Dishita2602.

**Comment by Dishita2602** [comment]
@yukti845 How can you close this issue before merging PR ?

**Comment by yukti845** [comment]
That was done by mistake.

**Comment by Dishita2602** [comment]
> That was done by mistake.

No worries
