### ISSUE TITLE
Ridge Regression - Base

### ISSUE THREAD

**Issue by AkanchhaBhadani** [Algo-Phantoms/Algo-ScriptML#19]
Would like to work on Ridge Regression. 
( I am GSSOC 2021 participant)

**Comment by SSHREYA71** [comment]
I would like to work on this issue, please assign this to me. ( I am GSSOC 2021 participant)

**Comment by ashwani-rathee** [comment]
Task: Set up the basic Ridge Regression code functionality that works
Level-3 : 25 Points

**Comment by ashwani-rathee** [comment]
@SSHREYA71 You have been assigned the task to setup the base for Ridge Regression.
Try to submit a PR in 5 days.

**Comment by SSHREYA71** [comment]
> @SSHREYA71 You have been assigned the task to setup the base for Ridge Regression.
> Try to submit a PR in 5 days.

Just saw this update, Thank You :) On it

**Comment by ashwani-rathee** [comment]
@SSHREYA71 What is your progress on this task?Any issues?

**Comment by SSHREYA71** [comment]
> @SSHREYA71 What is your progress on this task?Any issues? 2 days for a PR

Yes I will create the PR today itself

**Comment by SSHREYA71** [comment]
@ashwani-rathee  I had created the PR two days back itself, please look into

**Comment by ashwani-rathee** [comment]
#93 is clear

**Comment by ashwani-rathee** [comment]
Merged
