### ISSUE TITLE
Xgboost or AdaBoost

### ISSUE THREAD

**Issue by nakshatrasinghh** [Algo-Phantoms/Algo-ScriptML#20]
Would like to work on XGBoost or Adaboost from scratch (GSSoC' 21)

**Comment by srisatya1197** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant. I have worked on a similar problem before and want to work on this issue. Kindly assign this issue to me as a part of the GSSOC'21.

**Comment by ashwani-rathee** [comment]
Proper Channels have been formed for both of these,need to close these to avoid confusion
