### ISSUE TITLE
Adaboost and Apriori

### ISSUE THREAD

**Issue by NitiKaur** [Algo-Phantoms/Algo-ScriptML#21]
I am a GSSOC participant and would like to work on these two algorithms.Please assign it to me

**Comment by ashwani-rathee** [comment]
Hey @NitiKaur ,I have made two separate issues for this,it's a lot of work for a single person..since you have been trying to get a issue for quite sometime now,you would quickly want to grab one of those :)

**Comment by ashwani-rathee** [comment]
Proper channels/issues have been forward to continue work on those algorithms,need to close these to reduce confusion.
