### ISSUE TITLE
Add loss functions

### ISSUE THREAD

**Issue by RidhimaKohli** [Algo-Phantoms/Algo-ScriptML#24]
I would like to add loss functions as GS SOC 21 participant.

**Comment by Sibasish-Padhy** [comment]
I would like to add to loss functions for linera ,logistic,nns,SVM and some other classfication algorithms I know @ashwani-rathee

**Comment by ashwani-rathee** [comment]
@Sibasish-Padhy you don't need to do that :).I will be forming more issues today,you can get one from them.
