### ISSUE TITLE
Support Vector Machine-Base

### ISSUE THREAD

**Issue by ptnv-s** [Algo-Phantoms/Algo-ScriptML#25]
I am a GSSOC'21 participant and I would like to implement SVM from scratch. 
Can you please assign this to me?

**Comment by Anam118** [comment]
I want to contribute and implement SVM .Plz provide the same to me as a part of GSSOC Participant 2021.

**Comment by ashwani-rathee** [comment]
Task: Set up the basic SVM code functionality that works
Level-3 : 25 Points

**Comment by ashwani-rathee** [comment]
@ptnv-s  You have been assigned the task to setup the base for Support Vector Machine.
Try to submit a PR in 5 days.

**Comment by ashwani-rathee** [comment]
@ptnv-s What is your progress on this? Any issues? 2days for a PR

**Comment by ptnv-s** [comment]
@ashwani-rathee 
I have worked on the linear kernel svm and is working fine giving accuracy of 88.9% on titanic dataset
However, I was trying to work on writing code in which we have option to use different kernels in same SVM. 
![Screenshot from 2021-03-15 22-58-42](https://user-images.githubusercontent.com/72119231/111195234-0e108980-85e2-11eb-9e96-e16688f23883.png)

**Comment by ashwani-rathee** [comment]
#103 is not ready but @ptnv-s is still working on it.

**Comment by ashwani-rathee** [comment]
#103 still in progress

**Comment by ashwani-rathee** [comment]
Merged
