### ISSUE TITLE
KNN - Base

### ISSUE THREAD

**Issue by ananyade2412** [Algo-Phantoms/Algo-ScriptML#26]
Hello @kritikaparmar-programmer.
I am a GSSOC'21 participant. I would like to work on the issue of the K Nearest Neighbours Algorithm using Python. Please assign this issue to me.

**Comment by simarjeet30** [comment]
Hello @kritikaparmar-programmer.
I am a GSSOC'21 participant. I would like to work on the issue of the K Nearest Neighbours Algorithm using any of my three languages. I know python , C , C++ well. And i also have a good knowledge on DSA .Please assign this issue to me.

**Comment by ashwani-rathee** [comment]
Task: Set up the basic K Nearest Neighbours code functionality that works
Level-3 : 25 Points

**Comment by ashwani-rathee** [comment]
@ananyade2412 You have been assigned the task to setup the base for K Nearest Neighbours.
Try to submit a PR in 5 days.

**Comment by Amit366** [comment]
@ashwani-rathee Can I work on this issue??

**Comment by ashwani-rathee** [comment]
@ananyade2412 What is your progress on this? Any Issues? 2days for a PR

**Comment by ananyade2412** [comment]
Hello @ashwani-rathee. I'm working on the issue, sir.

**Comment by ashwani-rathee** [comment]
@ananyade2412 No PRs,this is to to be assigned again.

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant, and I would like to work on this issue. Please assign this issue to me.

**Comment by Simar05519** [comment]
Please assign this issue to me

**Comment by jprakash-1** [comment]
Hello, I am a GSSOC'21 participant, please assign this issue to me.

**Comment by Amit366** [comment]
> @ashwani-rathee Can I work on this issue??

Please assign it to me.

**Comment by goelesha** [comment]
@ashwani-rathee Please assign this issue to me

**Comment by Abheeshth** [comment]
Hello, I am a GSSOC'21 participant Can I work on this issue??

**Comment by Sibasish-Padhy** [comment]
@ashwani-rathee I am a gssoc 21 participant .Can i work on this issue

**Comment by ashwani-rathee** [comment]
@Abheeshth  You have been assigned the task to setup the base for K Nearest Neighbours.
Try to submit a PR in 5 days.

**Comment by Abheeshth** [comment]
Thanks @ashwani-rathee  I will try my best to submit a PR in 5 days

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by saumyasinghz** [comment]
@ashwani-rathee 
Hi, if this issue is still unassigned can I take it up?
Thank you.

**Comment by ashwani-rathee** [comment]
@saumyasinghz Sure go ahead

**Comment by saumyasinghz** [comment]
PR created. Please look into it.

**Comment by ashwani-rathee** [comment]
Merged
