### ISSUE TITLE
Bayesian Regression-Base

### ISSUE THREAD

**Issue by moyantri** [Algo-Phantoms/Algo-ScriptML#29]
I am a gssoc'21 participant and I want to work on it , please assign it to me

**Comment by ashwani-rathee** [comment]
Task: Set up the basic Bayesian Regression code functionality that works
Level-3 : 25 Points

**Comment by ashwani-rathee** [comment]
@moyantri You have been assigned the task to setup the base for Bayesian Regression.
Try to submit a PR in 5 days.

**Comment by ashwani-rathee** [comment]
@moyantri What is your progress on this?Any issues? 
How can I help?

**Comment by ashwani-rathee** [comment]
@moyantri No PRs,this needs to be reassigned again

**Comment by sakshi012000** [comment]
I am a GSSoC participant . Can you assign me this?

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me

**Comment by sakshi012000** [comment]
> I am a GSSoC participant . Can you assign me this?
@ashwani-rathee  can you please assign me this issue. I can send the PR as soon as possible.
Thank you

**Comment by goelesha** [comment]
Please assign this issue to me

**Comment by ashwani-rathee** [comment]
@goelesha You have been assigned the task to setup the base for Bayesian Regression.
Try to submit a PR in 5 days.

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by ashwani-rathee** [comment]
Merged
