### ISSUE TITLE
Lasso Regression - Base

### ISSUE THREAD

**Issue by divyanshu887** [Algo-Phantoms/Algo-ScriptML#30]
Hello @anubhavitis @dheerajkotwani @tarun26091999 @geekquad @todi-2000 
I am a gssoc'21 participant and I want to work on it , please assign it to me

**Comment by ashwani-rathee** [comment]
Task: Set up the basic Lasso Regression code functionality that works
Level-3 : 25 Points

**Comment by ashwani-rathee** [comment]
@divyanshu887 You have been assigned the task to setup the base for Lasso Regression.
Try to submit a PR in 5 days.

**Comment by hritikchaturvedi11** [comment]
I want to contribute to this issue.

**Comment by ashwani-rathee** [comment]
#64 is ready
