### ISSUE TITLE
Decision Tree and Random Forest implementation with explanation

### ISSUE THREAD

**Issue by ayush237** [Algo-Phantoms/Algo-ScriptML#31]
I am a GSSoC 21 participant(DISCORD username: smoky237 #5411), I can contribute to Decision Trees and Random Forest algorithms (including Bagging Concept) with proper implementation and Documentation. 
Kindly assign this work to me @geekquad  @kritikaparmar-programmer  @MAJOR-BEAST
#GSSoc

**Comment by ayush237** [comment]
I am a GSSoC 21 participant. I can contribute to Decision Trees and Random Forest algorithms (including Bagging Concept) with proper implementation and Documentation. Kindly assign this work to me @geekquad
DISCORD : smoky237

**Comment by ashwani-rathee** [comment]
@ayush237 Pls make separate issues for both,assigning both algorithms implementation won't be fair.I will assign you one of them of your liking as soon as you have made the issues.

**Comment by ayush237** [comment]
@ashwani-rathee  okay.. I am closing this issue and making separate issues for both. Thank You
