### ISSUE TITLE
XG BOOST , ADA BOOST , GRADIENT BOOST

### ISSUE THREAD

**Issue by dikshajoshi18** [Algo-Phantoms/Algo-ScriptML#32]
I am a GSSoC 21 participant. I can contribute to Decision Trees and Ada-Boost, Gradient Boost, and XgBoost algorithms (including Boosting Concept) with proper implementation and Documentation. Kindly assign this work to me @kritikaparmar-programmer @geekquad @MAJOR-BEAST
discord: diksha#6684

**Comment by ashwani-rathee** [comment]
@dikshajoshi18 Pls make separate issues for all 3,that way I can start assigning issues to you

**Comment by ashwani-rathee** [comment]
@geekquad we already have setup + issues for XGBOOST,ADBOOST.We would also kind of need a folder for Gradient Boost,if we are including it..

**Comment by Sibasish-Padhy** [comment]
hi I am gssoc 2021 participant.I would like to contribute to as many algos as I can.Can u assign me with this task??

**Comment by sayan9112** [comment]
Hi,
I am GSSOC'21 participant
please assign me this.

**Comment by subhanjan160901** [comment]
Hi, can I get this task assigned?

**Comment by geekquad** [comment]
> @geekquad we already have setup + issues for XGBOOST,ADBOOST.We would also kind of need a folder for Gradient Boost,if we are including it..

Yes @ashwani-rathee.

**Comment by ashwani-rathee** [comment]
Need to create another folder for Gradient Boost
