### ISSUE TITLE
Locally Weighted Regression (LOWESS)

### ISSUE THREAD

**Issue by dikshajoshi18** [Algo-Phantoms/Algo-ScriptML#33]
I am a GSSoC 21 participant. I can contribute to locally weighted regression(LOWESS)  with proper implementation and Documentation. Kindly assign this work to me @kritikaparmar-programmer @geekquad @MAJOR-BEAST
DISCORD: diksha#6684

**Comment by ashwani-rathee** [comment]
@dikshajoshi18 @geekquad We would need some setup for this one.

**Comment by geekquad** [comment]
Hey @dikshajoshi18, go ahead.
Just be sure to read the [Contributing Guidelines](https://github.com/Algo-Phantoms/Algo-ScriptML/blob/main/CONTRIBUTING.md) and follow accordingly. 
Create a folder. The directory of the folder should look like this:

> Locally Weighted Regression
>> name_of_the_file.py
>> README.md

Just be sure that we are accepting the implementation of the algorithm and not its application. No pre-trained models are allowed and no external modules/libraries are allowed. 
Feel free to use NumPy. 

Let me know if you have any queries. Thankyou.

**Comment by Sibasish-Padhy** [comment]
I am a GSSoC 21 participant. I can contribute to locally weighted regression(LOWESS) with proper implementation and Documentation. Kindly assign this work to me @kritikaparmar-programmer @geekquad @MAJOR-BEAST

**Comment by sayan9112** [comment]
Hi,
I am GSSOC'21 participant
please assign me this.

**Comment by ashwani-rathee** [comment]
@dikshajoshi18 Any updates?

**Comment by ashwani-rathee** [comment]
No updates,so this needs to be reassigned

**Comment by dikshajoshi18** [comment]
Sir actually I m facing issues in my laptop hardware.
Please extend the timeline.
I will do it surely by month end.

**Comment by earnsans** [comment]
@ashwani-rathee, hi I am a GSSOC'21  participant. I want to contribute to this issues. I have a pretty good knowledge about LOWESS regression. Can you please assign this issue to me.  I'll be using this [paper](http://home.eng.iastate.edu/~shermanp/STAT447/Lectures/Cleveland%20paper.pdf) for reference.

**Comment by geekquad** [comment]
Assigning this to @earnsans.

**Comment by earnsans** [comment]
Good evening sir,
 thank you for assigning this issue
<https://github.com/Algo-Phantoms/Algo-ScriptML/issues/33?_pjax=%23js-repo-pjax-container>
to
me.
 Could you please let me know the deadline for this ?

Yours sincerely,
Sanskrati Gupta

**Comment by ashwani-rathee** [comment]
#152 is a work in progress

**Comment by ashwani-rathee** [comment]
Merged
