### ISSUE TITLE
Perceptron-Base

### ISSUE THREAD

**Issue by aakriti1318** [Algo-Phantoms/Algo-ScriptML#34]
Hey, GSSoC 21 participant. 
I would like to contribute to Perceptronwith proper implementation and documentation. Kindly assign me this.

**Comment by ashwani-rathee** [comment]
Okay @aakriti1318,It has been assigned to you,you can start working on it.

**Comment by ashwani-rathee** [comment]
Task: Set up the basic Perceptron code functionality that works
Level-3 : 25 Points

**Comment by ashwani-rathee** [comment]
@aakriti1318 You have been assigned the task to setup the base for Perceptron.
Try to submit a PR in 5 days.

**Comment by aakriti1318** [comment]
Sure, will work under the deadline.

**Comment by ashwani-rathee** [comment]
@aakriti1318 #34 is almost ready,any help you need from my side?

**Comment by aakriti1318** [comment]
Yes, should I need to change anything?

**Comment by ashwani-rathee** [comment]
#34 is clear from my side,let's see how it turns out

**Comment by ashwani-rathee** [comment]
This can be successfully closed now
