### ISSUE TITLE
Adaboost-Base

### ISSUE THREAD

**Issue by ashwani-rathee** [Algo-Phantoms/Algo-ScriptML#35]
Task: Set up the basic Adaboost code functionality that works
Level-3 : 25 Points

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant. I want to work on this issue! Kindly assign this issue to me under GSSOC'21.

**Comment by ashwani-rathee** [comment]
@skybluee2001 You have been assigned the task to setup the base for Adaboost.
Try to submit a PR in 5 days

**Comment by skybluee2001** [comment]
@ashwani-rathee, thank you for assigning me this issue. I will submit a PR within 5 days.

**Comment by ashwani-rathee** [comment]
@skybluee2001 What is your progress on this?Any issues? 
How can I help?
2days to a PR

**Comment by skybluee2001** [comment]
@ashwani-rathee I have chosen a dataset to explain the implementation of the code. I will submit the PR by 17th March.

**Comment by skybluee2001** [comment]
@ashwani-rathee I have created a PR; kindly review it. 
Pull request #99

**Comment by skybluee2001** [comment]
@ashwani-rathee I have added my file in the .py format. Kindly review it.

**Comment by skybluee2001** [comment]
@ashwani-rathee, I have updated the code. Kindly review it.

**Comment by skybluee2001** [comment]
@ashwani-rathee, I have updated the code. Kindly review it. Let me know if any further modifications are required.

**Comment by ashwani-rathee** [comment]
#99 is almost ready

**Comment by ashwani-rathee** [comment]
Ready

**Comment by ashwani-rathee** [comment]
Merged
