### ISSUE TITLE
Apriori-Base

### ISSUE THREAD

**Issue by ashwani-rathee** [Algo-Phantoms/Algo-ScriptML#36]
Task: Set up the basic Apriori code functionality that works
Level-3 : 25 Points

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant. I want to work on this issue! Kindly assign this issue to me under GSSOC'21.

**Comment by anjiii-18** [comment]
Hii, I want to work under this issue for GSSOC 2021. Please assign this to me.

**Comment by ashwani-rathee** [comment]
@anjiii-18  You have been assigned the task to setup the base for  Apriori.
Try to submit a PR in 5 days.

**Comment by anjiii-18** [comment]
@ashwani-rathee Thank you for assigning me. I will submit PR in 5 days.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by anjiii-18** [comment]
@ashwani-rathee Can I use any dataset for the implementation of Apriori code?

**Comment by ashwani-rathee** [comment]
Actually we are looking for code implementation,you can use a simple dataset to explain you ideas

@anjiii-18  What is your progress on this?Any issues?How can I help?
2days to a PR
#64 #11 #44 are good examples of proper implementation by your fellow participants

**Comment by anjiii-18** [comment]
@ashwani-rathee I have chosen a dataset to explain the implementation of the code. I will submit the PR by 17th March.

**Comment by anjiii-18** [comment]
I have submitted the task. Kindly review my PR.

**Comment by anjiii-18** [comment]
@ashwani-rathee Please review my pull request #100.

**Comment by anjiii-18** [comment]
@ashwani-rathee I updated the code, kindly review it.

**Comment by anjiii-18** [comment]
@ashwani-rathee Kindly see if the code is correct.

**Comment by ashwani-rathee** [comment]
#100 is almost ready

**Comment by ashwani-rathee** [comment]
Merged
