### ISSUE TITLE
Linear Regression - Base

### ISSUE THREAD

**Issue by ashwani-rathee** [Algo-Phantoms/Algo-ScriptML#37]
Task: Set up the basic Linear Regression code functionality that works
Level-3 : 25 Points

**Comment by Abhinaba006** [comment]
I will like to work on this as well, I have previously made module similar to this, one can easily train data use my code

**Comment by ashwani-rathee** [comment]
@Abhinaba006  You have been assigned the task to setup the base for Linear Regression .
Try to submit a PR in 5 days.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by ashwani-rathee** [comment]
@Abhinaba006  #44  is almost ready
