### ISSUE TITLE
Logistic Regression - Base

### ISSUE THREAD

**Issue by ashwani-rathee** [Algo-Phantoms/Algo-ScriptML#38]
Task: Set up the basic Logistic Regression code functionality that works
Level-3 : 25 Points

**Comment by Abhinaba006** [comment]
I will like to work on this issue, I can make a module in python with functionality of .fit and .predict and other necessary method, so one can directly import it and use the code, the code will be well commented as well

**Comment by ashwani-rathee** [comment]
@Abhinaba006 has already been assigned a issue,this is still open for claim

**Comment by AkanchhaBhadani** [comment]
I would like to work on this issue. I am gssoc'21 participant. Please assign me this issue.

**Comment by ashwani-rathee** [comment]
@AkanchhaBhadani You have been assigned the task to setup the base for Logistic Regression  .
Try to submit a PR in 5 days.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by hritikchaturvedi11** [comment]
Hello, I'm a GSSOC'21 participant and would like to contribute to this project

**Comment by ashwani-rathee** [comment]
@AkanchhaBhadani What is your progress on this?Any issues?How can I help?
2days to a PR

**Comment by sakshi012000** [comment]
Hello, I'm a GSSOC'21 participant and would like to contribute to this project. Please assign me this

**Comment by AkanchhaBhadani** [comment]
> 
> 
> @AkanchhaBhadani What is your progress on this?Any issues?How can I help?
> 2days to a PR

I don't have any issue. Would be sending a PR today.

**Comment by ashwani-rathee** [comment]
#102 is ready

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by ashwani-rathee** [comment]
Merged
