### ISSUE TITLE
Principal Component Analysis - Base 

### ISSUE THREAD

**Issue by ashwani-rathee** [Algo-Phantoms/Algo-ScriptML#39]
Task: Set up the basic Principal Component Analysis code functionality that works
Level-3 : 25 Points

**Comment by Rutikab12** [comment]
I want to contribute to this issue as GSSoC'21 participant.

**Comment by ashwani-rathee** [comment]
@Rutikab12  You have been assigned the task to setup the base for Principal Component Analysis .
Try to submit a PR in 5 days.

**Comment by Rutikab12** [comment]
Okay.

**Comment by ashwani-rathee** [comment]
@Rutikab12 Yeah,It's expected to write a small example to show that your code works and it does what it's supposed to do.

**Comment by Bayesian4042** [comment]
Hey @ashwani-rathee can I work on this one as well ?

**Comment by Rutikab12** [comment]
@Bayesian4042 I have two days left for PR. I i am unable to complete it, then you can go for it.

**Comment by Rutikab12** [comment]
@ashwani-rathee my code is ok , is it? . I only have to pull it in .py extension, right?. I have closed my PR , which was pulled yesterday.

**Comment by ashwani-rathee** [comment]
I'll try to get it merged today,if it's working fine.I have got to check the algorithm though,on it.

**Comment by ashwani-rathee** [comment]
@Rutikab12 #74 is not yet ready
What is your progress on this?Any issues?How can I help?
2days to a PR
#64 #11 #44 are good examples of proper implementation by your fellow participants

**Comment by Rutikab12** [comment]
Yeah my new PR will be ready by today. One more thing, I was suppose to write the PCA module python code instead of importing it from sklearn , right?. @ashwani-rathee

**Comment by SNIGDHA2654** [comment]
I would like to work on this issue. I am a gssoc participant. Please assign it to me.

**Comment by Sibasish-Padhy** [comment]
@ashwani-rathee  I would like to work on this project can you assign this to me

**Comment by ashwani-rathee** [comment]
Needs to be reassigned

**Comment by ashwani-rathee** [comment]
@Sibasish-Padhy want to take it up?

**Comment by aishwaryachand** [comment]
hey can I work on this issue . I am a GSSOC21' participant . @ashwani-rathee

**Comment by ELITA04** [comment]
@ashwani-rathee
Hi, if this issue is still unassigned can I take it up?
Thank you.

**Comment by saumyasinghz** [comment]
@ashwani-rathee 
I am a participant GSSOC'21
I would like to contribute to this

**Comment by ashwani-rathee** [comment]
@ELITA04 Would you like to take this up and continue on the work?

**Comment by ELITA04** [comment]
@ashwani-rathee, Yes I'd like to.

**Comment by ashwani-rathee** [comment]
@ELITA04 Go ahead
