### ISSUE TITLE
Lets work 

### ISSUE THREAD

**Issue by codelight2711** [Algo-Phantoms/Algo-ScriptML#4]
Let me update few algorithms

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant. I want to work on this issue by updating the algorithms and explaining the algorithms' inner workings. Kindly assign me this issue under GSSOC'21.

**Comment by ashwani-rathee** [comment]
@codelight2711 @skybluee2001 
> Let me update few algorithms

Pls try to make issues for one algorithm at a time.

**Comment by skybluee2001** [comment]
Hii...I want to update the Linear Regression model. I will present its inner workings in a clear and usable manner. Please could you assign it to me under GSSOC'21 so that I can start working on it!!

**Comment by ashwani-rathee** [comment]
Proper channels/issues have been formed and this needs to be closed to avoid confusion
