### ISSUE TITLE
Decision Tree - Base

### ISSUE THREAD

**Issue by ayush237** [Algo-Phantoms/Algo-ScriptML#41]
I am a GSSoC 21 participant (DISCORD username: smoky237 #5411), I can contribute to the Decision Trees algorithm with proper implementation and Documentation on a dataset.
Kindly assign this work to me @geekquad @kritikaparmar-programmer @MAJOR-BEAST
#GSSoc

**Comment by ashwani-rathee** [comment]
Task: Set up the basic Decision Tree code functionality that works
Level-3 : 25 Points

**Comment by ashwani-rathee** [comment]
@ayush237  You have been assigned the task to setup the base for Decision Tree .
Try to submit a PR in 5 days.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by ashwani-rathee** [comment]
@ayush237  What is your progress on this?Any issues?How can I help?
2days to a PR

**Comment by ayush237** [comment]
@ashwani-rathee  Hi . Its almost done, no issues yet. I will pull up the PR by tonight

**Comment by ashwani-rathee** [comment]
#125 is not ready

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by ashwani-rathee** [comment]
@asimaries would you like to take this up?

**Comment by ayush237** [comment]
@ashwani-rathee I have already updated the PR 4 days back regarding decision tree.. kindly check

**Comment by ayush237** [comment]
@ashwani-rathee please check here h: ttps://github.com/Algo-Phantoms/Algo-ScriptML/pull/153#issuecomment-819606592

**Comment by asimaries** [comment]
> @asimaries would you like to take this up?

sure

**Comment by ayush237** [comment]
> > @asimaries would you like to take this up?
> 
> sure

sorry, but I have already done it 6 days ago. https://github.com/Algo-Phantoms/Algo-ScriptML/pull/153# (my PR is not reviewed yet)
