### ISSUE TITLE
Random Forest - Base

### ISSUE THREAD

**Issue by ayush237** [Algo-Phantoms/Algo-ScriptML#42]
I am a GSSoC 21 participant (DISCORD username: smoky237 #5411), I can contribute to the Random Forest algorithm(including bagging concept) with proper implementation and Documentation on a dataset.
Kindly assign this work to me @geekquad @kritikaparmar-programmer @MAJOR-BEAST
#GSSoc

**Comment by dikshajoshi18** [comment]
I am a GSSoC 21 participant (DISCORD username: diksha#6684 ), I can contribute to the Random Forest algorithm with implementation and Explanation applying it on a dataset.
Kindly assign this work to me @ashwani-rathee @geekquad @kritikaparmar-programmer @MAJOR-BEAST
#GSSoc

**Comment by simarjeet30** [comment]
I am a GSSoC 21 participant , I can contribute to the Random Forest algorithm  in pythin/c/c++.
Kindly assign this work to me @ashwani-rathee @geekquad @kritikaparmar-programmer

**Comment by JanhaviSoni** [comment]
Please assign it @ashwani-rathee

**Comment by ashwani-rathee** [comment]
@simarjeet30  You have been assigned the task to setup the base for Random Forest .
Try to submit a PR in 5 days.

**Comment by ashwani-rathee** [comment]
@JanhaviSoni I will be forming more issues today,you can get one from them :)30 seconds difference in comment quite amazed

**Comment by JanhaviSoni** [comment]
Okay. Thanks for looking into this .

**Comment by simarjeet30** [comment]
@ashwani-rathee  In which language am I supposed to do this work

**Comment by ashwani-rathee** [comment]
@simarjeet30 Can you please check the readme.md and contribution guidelines?It's mentioned there and lot of other important details on how to proceed with tasks

**Comment by ashwani-rathee** [comment]
@simarjeet30  #76 is progressing but not yet ready
Any issues,How can I help?

**Comment by simarjeet30** [comment]
mam i have imported numpy as np .sorry for these things .please have a look
now .Is there anything else needed

**Comment by asimaries** [comment]
I would Like to work on this issue

**Comment by ashwani-rathee** [comment]
@asimaries You have been assigned the task to setup the base for Random Forest .
Try to submit a PR in 5 days.

**Comment by SNIGDHA2654** [comment]
@ashwani-rathee I would like to work on this issue. I am a gssoc participant. Kindly, assign it to me.

**Comment by asimaries** [comment]
> @asimaries You have been assigned the task to setup the base for Random Forest .
> Try to submit a PR in 5 days.

actually some has already updated the readme file so I have to Implement it on that bases or make my own readme?
#98 is already merged

**Comment by ashwani-rathee** [comment]
@asimaries You are supposed to write the base code only with test of checking it properly

**Comment by asimaries** [comment]
> @asimaries You are supposed to write the base code only with test of checking it properly

I have made a PR, please review it #128

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by ashwani-rathee** [comment]
Merged
