### ISSUE TITLE
XGBoost , explanation and implementation 

### ISSUE THREAD

**Issue by dikshajoshi18** [Algo-Phantoms/Algo-ScriptML#43]
I am a GSSoC 21 participant (DISCORD username: diksha#6684 ), I can contribute to the XGBoost algorithm with proper implementation and Documentation on a dataset.
Kindly assign this work to me @ashwani-rathee @geekquad @kritikaparmar-programmer @MAJOR-BEAST
#GSSoc

**Comment by ashwani-rathee** [comment]
@dikshajoshi18 pls don't open issues,that have already been opened.It makes managing issues and assigning tasks difficult.

**Comment by dikshajoshi18** [comment]
alright, sure, sorry about that
