### ISSUE TITLE
Will like to add the automated contribution section in read me

### ISSUE THREAD

**Issue by rohank2502** [Algo-Phantoms/Algo-ScriptML#48]
I will like to add a feature in read me which will update the list of contributors automatically !!

**Comment by ashwani-rathee** [comment]
@geekquad Do we need this feature?I like the idea

**Comment by geekquad** [comment]
Hey @rohank2502, how exactly are you planning to do so?
By using the all-contributors bot?

**Comment by rohank2502** [comment]
No I will add one link of image which I have added to my own repository https://github.com/rohank2502/Learn-GITHUB   Have a look at read me of this .

**Comment by geekquad** [comment]
Hey @rohank2502, thank you for the effort but I know about the **contrib.rocks**.
Will add it in the later phase of the program.

**Comment by rohank2502** [comment]
> 
> 
> Hey @rohank2502, thank you for the effort but I know about the **contrib.rocks**.
> Will add it in the later phase of the program.

Will like to work on this do consider me !!
