### ISSUE TITLE
Linear Regression - Documentation

### ISSUE THREAD

**Issue by ashwani-rathee** [Algo-Phantoms/Algo-ScriptML#49]
Task : Create detailed documentation of the Linear Regression ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by aanchalsethi** [comment]
Hey! 
i would like to create a document on linear regression.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by SSHREYA71** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project. Please assign it to me

**Comment by eishagoel15** [comment]
I am a Gssoc participant and I can contribute to this issue by writing a well neat and clean documentation for this. So plz assign this issue to me.

**Comment by harleenkaur76** [comment]
hello ...I am agssoc participant and would love to contribute to this course it will be great if you can assign this project to me

**Comment by harleenkaur76** [comment]
hello ...I am a gssoc participant and would love to contribute to this issue it will be great if you can assign this project to me

**Comment by sayan9112** [comment]
Hi,
I am GSSOC'21 participant
please assign me this.

**Comment by ashwani-rathee** [comment]
Sure @aanchalsethi  ,You have been assigned the task to create detailed documentation of Linear Regression.
Try to submit a PR in 2 days.

**Comment by ashwani-rathee** [comment]
@aanchalsethi #83 is almost ready to be merged

**Comment by ashwani-rathee** [comment]
Merged
