### ISSUE TITLE
KNN, Linear and Logistic Regression

### ISSUE THREAD

**Issue by arpitmaheshwari213** [Algo-Phantoms/Algo-ScriptML#5]
Hi, 
I can update KNN, Linear, and Logistic Regression.
Can you please assign it to me?
I am a participant in GSSOC-21.

**Comment by Amulya310** [comment]
Hey, I would really like to work on this issue under GSSOC'21 .Kindly consider assigning this to me!!

**Comment by mehak2323** [comment]
Hi, I would like to work on this issue. I'm a GSSOC 21 participant. It'd be great if you would assign it to me :)

**Comment by RhuthuHegde** [comment]
Can I work on this issue, under gssoc'21?

**Comment by RiaKokate** [comment]
Hey @arpitmaheshwari213 
I hope you are fine and doing well.
I would like to work on this issue under GSSOC'21. Can you please assign the following to me?

**Comment by kritikaparmar-programmer** [comment]
Hey, @arpitmaheshwari213 assigning you the issue on the basis of first come.

**Comment by RiaKokate** [comment]
Thanks you so much Mam for this opportunity.

**Comment by SSHREYA71** [comment]
I will like to contribute on this issue under GSSOC'21 please assign it to me

**Comment by ashwani-rathee** [comment]
Proper issues have been formed for ths,this needs to be closed to avoid confusion
