### ISSUE TITLE
Logistic Regression - Documentation

### ISSUE THREAD

**Issue by ashwani-rathee** [Algo-Phantoms/Algo-ScriptML#50]
Task : Create detailed documentation of the Logistic Regression ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by sakshi012000** [comment]
Hi,
I am GSSOC'21 participant
please assign me this.

**Comment by ashwani-rathee** [comment]
Sure @sakshi012000  ,You have been assigned the task to create detailed documentation of Logistic Regression.
Try to submit a PR in 2 days.

**Comment by sakshi012000** [comment]
> Sure @sakshi012000 ,You have been assigned the task to create detailed documentation of Logistic Regression.
> Try to submit a PR in 2 days.

yes sure . thank you

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by harleenkaur76** [comment]
hello ...I am a gssoc participant and would love to contribute to this issue it will be great if you can assign this project to me. i will do my best to write clean and understandable documentation

**Comment by sakshi012000** [comment]
@ashwani-rathee  I have sent a PR . Please inform me for any modifications.
thankyou

**Comment by ashwani-rathee** [comment]
Merged
