### ISSUE TITLE
Logistic Regression and Linear Regression -Implementation 

### ISSUE THREAD

**Issue by KISHU-123** [Algo-Phantoms/Algo-ScriptML#52]
I can do the implementation of linear regression and logistic regression form scratch. 
I am a gssoc'21 participant.

**Comment by ashwani-rathee** [comment]
@KISHU-123 Linear Regression and Logistic Regression base setup have already been assigned,you can take up documentation tasks by claiming issue in issues list

**Comment by hritikchaturvedi11** [comment]
I wanted to do the implementation of both lasso and logistic regression.

**Comment by ashwani-rathee** [comment]
Proper channels have been formed this not neccessary
