### ISSUE TITLE
Decision Tree -Documentation

### ISSUE THREAD

**Issue by aishwaryachand** [Algo-Phantoms/Algo-ScriptML#54]
Hey @ashwani-rathee I would like to work on the documentation of the Decision Tree. I am a GSSOC21 participant.Pls assign me this issue.

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the Decision Tree ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by ashwani-rathee** [comment]
Sure @aishwaryachand  ,You have been assigned the task to create detailed documentation of Decision Tree.
Try to submit a PR in 2 days.

**Comment by sanyadeveloper2000** [comment]
Hey I would like to work on this issue. I have experience in technical writing. Pls assign me this task.
Thanks

**Comment by neha07kumari** [comment]
Hey!! I would like to work on the documentation of the Decision Tree. I am a GSSOC21 participant. Please assign me this issue. @ashwani-rathee

**Comment by ashwani-rathee** [comment]
@sanyadeveloper2000 @neha07kumari This issue has already been resolved by @aishwaryachand  and merged too,please claim new issues
