### ISSUE TITLE
KMeans - Documentation

### ISSUE THREAD

**Issue by ELITA04** [Algo-Phantoms/Algo-ScriptML#58]
Hello, I am a GSSOC'21 participant and I want to work on the documentation of KMeans clustering algorithm. Can you assign it to me?

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the KMeans ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by ashwani-rathee** [comment]
Sure @ELITA04  ,You have been assigned the task to create detailed documentation of KMeans.
Try to submit a PR in 2 days.

**Comment by hritikchaturvedi11** [comment]
Hey! I would like to work on it too.
