### ISSUE TITLE
Multilayer Perceptron -Documentation

### ISSUE THREAD

**Issue by sal-glitch** [Algo-Phantoms/Algo-ScriptML#59]
Hey Since someone is already assigned the code, can I be assigned on the documentation? I am a GSSOC participant

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the Multilayer Perceptron ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by ashwani-rathee** [comment]
Sure @sal-glitch ,You have been assigned the task to create detailed documentation of Multilayer Perceptron .
Try to submit a PR in 2 days.

**Comment by sal-glitch** [comment]
Hey I have given a PR for this, do let me know if I need to change anything.

**Comment by subhanjan160901** [comment]
Is there any issues left? can I work on it? I am a gssoc participant

**Comment by ashwani-rathee** [comment]
Merged
