### ISSUE TITLE
K-Means, Regressions, Decision tree

### ISSUE THREAD

**Issue by sudipg4112001** [Algo-Phantoms/Algo-ScriptML#6]
I would like to work on K-means, decision tree, linear regression, logistic regression, random forest. I am a participant of GSSOC'21.

**Comment by Ankitasareen** [comment]
Hey can I work on this, under GSSOC'21?

**Comment by psyduck1203** [comment]
Hey, @sudipg4112001 @Ankitasareen can we just work on one algorithm each so there everyone gets a chance?

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant. I want to work on this issue. I can contribute to any of the 3 algorithms. Kindly assign me this issue as a part of the GSSOC'21.

**Comment by Dishita2602** [comment]
Hey, I am willing to work on K- means, Regression and decision tree in python by using scikit learn. I am currently participant at GSSoC'21 and want to work on this issue.

**Comment by ashwani-rathee** [comment]
Proper issues have been formed for this and it needs to closed to avoid confusion
