### ISSUE TITLE
Elastic Net- Base

### ISSUE THREAD

**Issue by sal-glitch** [Algo-Phantoms/Algo-ScriptML#60]
Hey! I would like to work on the code for Elastic net, its implementation from scratch. Could I be assigned this issue. I am a GSSOC participant.

**Comment by ashwani-rathee** [comment]
Task: Set up the basic Multilayer Elastic Net code functionality that works
Level-3 : 25 Points

**Comment by sal-glitch** [comment]
Hey thanks! Can I get this assigned please?

**Comment by ashwani-rathee** [comment]
@sal-glitch one task at a time :) you asked for documentation first

**Comment by sal-glitch** [comment]
Yeah sure no problem. Will do this after I am done with the other one!

**Comment by Bayesian4042** [comment]
Hey @ashwani-rathee can I work on elastic net regularisation ?

**Comment by hritikchaturvedi11** [comment]
Hey, Can I work on this issue??

**Comment by subhanjan160901** [comment]
Can I do this, I am a gssoc participant... I have worked with Elastic nets

**Comment by sal-glitch** [comment]
Hey @ashwani-rathee I have given PR for the previous task, if you don't mind can I be assigned this one so that I can start working asap?

**Comment by ashwani-rathee** [comment]
Sure @sal-glitch  ,You have been assigned the task to create detailed documentation of  Elastic Net.
Try to submit a PR in 2 days.

**Comment by sal-glitch** [comment]
@ashwani-rathee Yes thank you! Will give a PR within 2 days!

**Comment by ashwani-rathee** [comment]
#109 is ready to be merged

**Comment by ashwani-rathee** [comment]
Merged
