### ISSUE TITLE
Stochastic Gradient descent algorithm with full explanation.

### ISSUE THREAD

**Issue by captainra1** [Algo-Phantoms/Algo-ScriptML#61]
I am a GSSOC's participant please assign me this issue.

**Comment by ashwani-rathee** [comment]
@geekquad Do we need setup for this?

**Comment by hritikchaturvedi11** [comment]
I want to work on this issue.

**Comment by captainra1** [comment]
> @geekquad Do we need setup for this?

I really don't understand what does setup means here??
but assign me this, here is my plan:
1. explain what is SGD(Stochastic Gradient descent)
2. when to use SGD.
3. How it is different from other ML algos
4. How and what different types of ML algo can be used with SGD.
5.coding for SGD
6.Used case( model based on SGD).

**Comment by subhanjan160901** [comment]
Can I work on this issue. I have worked with SGD quite a number of times and i am sure I can do this quite well

**Comment by geekquad** [comment]
Thankyou @ashwani-rathee.
Hey @captainra1, 
Assigning the issue to you. Make sure you have read the Contributing Guidelines. 
We are looking for an implementation of the algorithm and not its application. 
Please create a folder for the same. The directory of the folder should look like this:

> Stochastic Gradient Descent
>> name_of_the_file.py
>> README.md

Let me know if you have any queries. Thankyou.

**Comment by captainra1** [comment]
> Thankyou @ashwani-rathee.
> Hey @captainra1,
> Assigning the issue to you. Make sure you have read the Contributing Guidelines.
> We are looking for an implementation of the algorithm and not its application.
> Please create a folder for the same. The directory of the folder should look like this:
> 
> > Stochastic Gradient Descent
> > > name_of_the_file.py
> > > README.md
> 
> Let me know if you have any queries. Thankyou.

thanks for assigning me this issue.

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by ashwani-rathee** [comment]
Merged
