### ISSUE TITLE
Neural network - Documentation

### ISSUE THREAD

**Issue by aanchalsethi** [Algo-Phantoms/Algo-ScriptML#65]
May i create the documentation for the neural network?

**Comment by ashwani-rathee** [comment]
@aanchalsethi There is no specific folder for neural network as of now #47 .It's not exactly clear what will go in that,this task can be assigned when the task is more clear to me. Please take up another unassigned issue :)

**Comment by aanchalsethi** [comment]
okay sir

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by aanchalsethi** [comment]
May i work on this issue now?

**Comment by ashwani-rathee** [comment]
@aanchalsethi would you like to take this up?

**Comment by aanchalsethi** [comment]
yes sure sir!

**Comment by ashwani-rathee** [comment]
@aanchalsethi Sure,go ahead

**Comment by aanchalsethi** [comment]
There is no folder for the neural networks. Should I create one?

**Comment by ashwani-rathee** [comment]
Merged
