### ISSUE TITLE
Lasso Regression - Documentation

### ISSUE THREAD

**Issue by divyanshu887** [Algo-Phantoms/Algo-ScriptML#66]
I want to work on the documentation of Lasso Regression algorithm. Can you assign it to me?
@ashwani-rathee

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the Lasso Regression ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by ashwani-rathee** [comment]
Sure @divyanshu887 ,You have been assigned the task to create detailed documentation of Lasso Regression.
Try to submit a PR in 2 days.

**Comment by ashwani-rathee** [comment]
#64 is ready
