### ISSUE TITLE
DBSCAN - Documentation

### ISSUE THREAD

**Issue by hritikchaturvedi11** [Algo-Phantoms/Algo-ScriptML#69]
Can I work on this issue???

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the DBSCAN ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by aanchalsethi** [comment]
May i work on this documentation?

**Comment by ashwani-rathee** [comment]
@aanchalsethi Let's get #83 merged first,you have claimed both base and documentation,then you can work on either of your choice

**Comment by asimaries** [comment]
I would like to work on this Issue

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant, and I would like to work on this issue. Please assign this issue to me.

**Comment by Charanjeev-2k2** [comment]
Hi @ashwani-rathee I am eager to contribute to this issue. Kindly assign it to me.

**Comment by ashwani-rathee** [comment]
@Charanjeev-2k2 Sure,go ahead

**Comment by aanchalsethi** [comment]
Sir i already have pulled the request for this document.

**Comment by yukti845** [comment]
@Charanjeev-2k2 what are the updates?

**Comment by Charanjeev-2k2** [comment]
> @Charanjeev-2k2 what are the updates?
On it
Had semester end exams in between. Will be putting up the pr before May 31st
Sorry for the delay

**Comment by Manasi2001** [comment]
Can I work on this @yukti845 @geekquad @ashwani-rathee?

**Comment by geekquad** [comment]
Already there @Manasi2001.
