### ISSUE TITLE
SVM, Random Forest and XGBoost

### ISSUE THREAD

**Issue by akshitadixit** [Algo-Phantoms/Algo-ScriptML#7]
Hey I would like to work on these algorithms in python. Kindly assign.

**Comment by JanhaviSoni** [comment]
@geekquad please assign Random Forest Regression to me

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant. I have worked on similar problems before and want to contribute to this issue. Kindly assign me this issue as a part of the GSSOC'21.

**Comment by Aditi0102** [comment]
Hello, I want to contribute to the issue and build SVM, Random forest and XGBoost algorithms from scratch and code them in an efficient and presentable manner.

**Comment by tanya12181** [comment]
hello, i have already implemented svm and random forest from scratch. Kindly assign this issue to me.

**Comment by Sibasish-Padhy** [comment]
hello,I am currently a GSSoC 2021 paticipant and want to contribute for svm and XGBoost from scratch.Kindly assign this issue to me @ashwani-rathee

**Comment by akshitadixit** [comment]
> Hey I would like to work on these algorithms in python. Kindly assign.

@ashwani-rathee I raised the issue 9days ago, kindly assign it to me under GSSOC

**Comment by ashwani-rathee** [comment]
@akshitadixit SVM,XGboost have already been assigned,you can claim RandomBoost one if nobody has claimed it before you in last 2 days

**Comment by ashwani-rathee** [comment]
Proper issues have been formed for this issue(multiple issue and need to close this to avoid confusion :)
