### ISSUE TITLE
Adaboost - Documentation

### ISSUE THREAD

**Issue by hritikchaturvedi11** [Algo-Phantoms/Algo-ScriptML#71]
As this issue hadn't been raised earlier. I would like to work on this issue.

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the Adaboost ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by SNIGDHA2654** [comment]
I would like to contribute could you please assign me this task.  I am a gssoc participant.

**Comment by harleenkaur76** [comment]
@ashwani-rathee i am a gssoc participant and i would love to contribute to this project and would try my best to explain it in the best possible way

**Comment by hritikchaturvedi11** [comment]
@ashwani-rathee kindly assigned the issue as I can submit the pr.

**Comment by skybluee2001** [comment]
Hii...I am a GSSOC'21 participant, and I would like to work on this issue. Kindly assign me this issue.

**Comment by surbhi2408** [comment]
@ashwani-rathee I would like to contribute could you please assign me this task. I am a GSSoC'21 participant.

**Comment by ashwani-rathee** [comment]
@surbhi2408 would you like to take this up?

**Comment by surbhi2408** [comment]
> @surbhi2408 would you like to take this up?

Yes, sure

**Comment by ashwani-rathee** [comment]
@surbhi2408 Sure,go ahead

**Comment by ashwani-rathee** [comment]
Merged
