### ISSUE TITLE
Support Vector Machine - Documentation

### ISSUE THREAD

**Issue by hritikchaturvedi11** [Algo-Phantoms/Algo-ScriptML#73]
I would like to write the whole analysis of this algorithm and documentation.

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the Support Vector Machine ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by SNIGDHA2654** [comment]
I would like to create detailed documentation of SVM. Please assign me this task. I am a gssoc participant.

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the SVM ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by ashwani-rathee** [comment]
Sure @SNIGDHA2654 ,You have been assigned the task to create detailed documentation of SVM.
Try to submit a PR in 2 days.

**Comment by surbhi2408** [comment]
It's already been more than 2 days @ashwani-rathee please if you could assign this task to me. I am also a GSSoC'21 participant.

**Comment by ashwani-rathee** [comment]
@surbhi2408 It's clear from my side, we are now waiting for admin's decision on merging

**Comment by ashwani-rathee** [comment]
Merged
