### ISSUE TITLE
C5.0 Decision Tree

### ISSUE THREAD

**Issue by khanfarhan10** [Algo-Phantoms/Algo-ScriptML#8]
There is no implementation of the `C5.0 Decision Tree in Python` available anywhere on the internet.

Even `scikit-learn` has `C4.0` or `C4.5` or `CART` algorithm implemented under the hood.

So it would be great to have C5.0 Decision Tree implemented over the same.

(P.S. - It is not an easy task,)

**Comment by geekquad** [comment]
Sounds amazing.
Would you like to work on the same?

**Comment by ashwani-rathee** [comment]
@geekquad Would we need separate folder for this one?

**Comment by geekquad** [comment]
Yes @ashwani-rathee, 
@khanfarhan10 please create a new folder.
The directory of the folder should look like this:

> C5.0 Decision Tree
>> name_of_the_file.py
>> README.md

Just be sure that we are accepting the implementation of the algorithm and not its application. No pre-trained models are allowed and no external modules/libraries are allowed. 
Feel free to use NumPy. 

Let me know if you have any queries. Thank you.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by khanfarhan10** [comment]
Could you please assign someone else for this task? Actually I'm not a participant but a mentor for another project.

**Comment by ashwani-rathee** [comment]
@Hamza3226 Do you want to work on this issue?

**Comment by Simar05519** [comment]
Please assign me some other issue so that I can work

**Comment by SNIGDHA2654** [comment]
I would like to work on this issue. I am a gssoc participant.

**Comment by ashwani-rathee** [comment]
@SNIGDHA2654,You have been assigned the task to write Decision Tree code base functionality that works.
Try to submit a PR in 5 days.

**Comment by ashwani-rathee** [comment]
Merged

**Comment by khanfarhan10** [comment]
Is the algorithm implemented or will it not be worked upon?
@ashwani-rathee ??
