### ISSUE TITLE
Adding New Module/Class for Normalization and Standardization - Base

### ISSUE THREAD

**Issue by sujoy-coder** [Algo-Phantoms/Algo-ScriptML#85]
HI @ashwani-rathee , I would like to add a new feature that is adding new `Module/Class for Normalization and Standardization` .
We know before train the data to some specific ML Model we have to  Normalized or Standardized the dataset to get better accuracy.
So I am a GSSoC participant. I would like to work on the same issue

Thank You 🙏

**Comment by ashwani-rathee** [comment]
@geekquad  What do you think?

**Comment by sujoy-coder** [comment]
Hello @ashwani-rathee @geekquad ,
Any updates regarding this issue ?

**Comment by geekquad** [comment]
Hey @sujoy-coder, assigning you with the same.

**Comment by sujoy-coder** [comment]
Okay @geekquad, I am started working on it.

Thank You :)

**Comment by sujoy-coder** [comment]
Hey @geekquad My idea is :

- create a new folder in ROOT DIRECTORY and named it `Preprocessing`
- inside that create `new python file` 
- then the code will be inside that python file ( OOPs and python Class)

May I continue in that way ?
Please let me know for any other procedure
