### ISSUE TITLE
Naive Bayes -Documentation

### ISSUE THREAD

**Issue by aishwaryachand** [Algo-Phantoms/Algo-ScriptML#86]
I would like to work on this issue. Pls, assign me.

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the Naive Bayes ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by ashwani-rathee** [comment]
Sure @aishwaryachand  ,You have been assigned the task to create detailed documentation of Naive Bayes.
Try to submit a PR in 2 days.

**Comment by jaimehta1912** [comment]
@ashwani-rathee It's already 2 days .Can you please assign me this issue I have already made readme.md file for Naiye Bayes .Kindly assign me this issue .I am a Gssoc 2021 participant .I will make sure. I will make sure a PR for documentation of naive Bayes will be in the upcoming 2 Hours

**Comment by aishwaryachand** [comment]
I am almost done.I will make a PR by today.

**Comment by jaimehta1912** [comment]
@ashwani-rathee  I want to add some more  information in naive Bayes .kindky assign me the issue
