### ISSUE TITLE
Adding Decision Tree classification Algorithm build from scratch 

### ISSUE THREAD

**Issue by Spidy-Coder** [Algo-Phantoms/Algo-ScriptML#88]
I have made a pure decision tree algorithm representation in python from scratch. This issue fixes following issues:-

- [x] No plagiarism

- [x] Build from scratch

- [x] Fully demonstrated with comments

- [x] Contains .ipnb format

- [x] Contains useful resources in that same .ipnb file for newbie references

### Link of my code repo that I will be adding after assigning this issue to me --->

[https://github.com/Spidy-Coder/Decision_Tree_Classifier](url)

**Comment by Spidy-Coder** [comment]
Hello,

I haven't got any reply for my issue. So, kindly look into it. I want to contribute my decision tree classifier to this repo. It will a value addition if it will happen. Thank you :)

**Comment by ashwani-rathee** [comment]
Needs to be reassigned

**Comment by utkarshxy** [comment]
Would like to work on this issue asap. Kindly assign, please. 
Gssoc21'

**Comment by ashwani-rathee** [comment]
@utkarshxy Sure,go ahead

**Comment by ashwani-rathee** [comment]
Duplicate
