### ISSUE TITLE
KNN - Documentation

### ISSUE THREAD

**Issue by shraiyya** [Algo-Phantoms/Algo-ScriptML#89]
I would like to add K-Nearest Neighbors algorithm documentation.
I am a GSSOC'21 participant

**Comment by yashkumar7889** [comment]
Hello, I am a GSSOC'21 participant. I would like to add documentation for K-Nearest Neighbors Algorithm along with the code.

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the K-Nearest Neighbors ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by ashwani-rathee** [comment]
Sure @shraiyya  ,You have been assigned the task to create detailed documentation of K-Nearest Neighbors.
Try to submit a PR in 2 days.

**Comment by neha07kumari** [comment]
Hey!! I'm a GSSOC"21 participant. Please assign me this issue . I would like to contribute to it.
@ashwani-rathee

**Comment by goelesha** [comment]
Pls assign this issue to me

**Comment by Ishan-Tewari** [comment]
Hey! I'm a GSSOC 21 participant. I would like to contribute to this issue.

**Comment by einhawking** [comment]
I am a participant GSSOC'21
I would like to contribute in this

**Comment by ashwani-rathee** [comment]
@Ishan-Tewari Would you like to take this up?

**Comment by aabhapingle** [comment]
@ashwani-rathee Hi! I am a GSSOC 21 participant. I would like to contribute to this issue.

**Comment by ashwani-rathee** [comment]
@aabhapingle Sure,go ahead

**Comment by sameeksharl** [comment]
@ashwani-rathee @neha07kumari Hi , I am sameeksha, participant of GSSoC 21 . Could you pls assign this issue to me??

**Comment by ashwani-rathee** [comment]
Merged
