### ISSUE TITLE
Principal Component Analysis - Documentation

### ISSUE THREAD

**Issue by ashwani-rathee** [Algo-Phantoms/Algo-ScriptML#91]
Task: Update the Readme.md to explain the process behind Principal Component Analysis  as well as you can
Level-1 : 10 Points

**Comment by ashwani-rathee** [comment]
@Simar05519 Would you like to work on this?

**Comment by Simar05519** [comment]
OK, I can work on it.

**Comment by ashwani-rathee** [comment]
Sure @Simar05519  ,You have been assigned the task to create detailed documentation of Principal Component Analysis .
Please see the documentation guidelines first.
Try to submit a PR in 2 days.

**Comment by Simar05519** [comment]
Sure, will do that.

**Comment by aayushi1908** [comment]
Hello.
I'm a GSSOC'21 participant and I want to work on this issue.

**Comment by guptaa98** [comment]
I'm a Gssoc'21 participant. 
Can i work on this issue?

**Comment by ashwani-rathee** [comment]
@guptaa98 Would you like to take this up?

**Comment by guptaa98** [comment]
@ashwani-rathee yes I would like to work on this issue.

**Comment by ashwani-rathee** [comment]
@guptaa98 Sure,go ahead

**Comment by ashwani-rathee** [comment]
Merged
