### ISSUE TITLE
Ridge Regression-Documentation

### ISSUE THREAD

**Issue by divyanshu887** [Algo-Phantoms/Algo-ScriptML#92]
I want to work on the documentation of Ridge Regression algorithm. Can you assign it to me?
@ashwani-rathee

**Comment by ashwani-rathee** [comment]
Task : Create detailed documentation of the Ridge Regression ML algorithm by updating readme.md
Level-1 : 10 points

**Comment by ashwani-rathee** [comment]
@divyanshu887  ,You have been assigned the task to create detailed documentation of Ridge Regression.
Try to submit a PR in 2 days.

**Comment by divyanshu887** [comment]
@ashwani-rathee 
Done
Check the pr Ref (#64)
